<html>
    <head>
        <title>Welcome into matrix...</title>
        <script src="scripts/main.js" type="text/javascript"></script>
        <link rel="stylesheet" href="common.css" type="text/css"/>
    </head>
    <body>
        <div class="background-img">
            <div id="morfeus">
                <div id="message">Выбери свою таблетку</div>
            </div>
        </div>
    </body>
</html>